#!/bin/bash
set -e

cd openwrt-openwisp-monitoring/

# format lua files
lua-format -i --config=luaformat.config \
	files/sbin/*.lua \
	files/lib/openwisp/*.lua \
	tests/*.lua \
	tests/test_files/*.lua
