#!/bin/bash
set -e

# format shell scripts
shfmt -w -l .
shfmt -w -l openwisp-monitoring/files/monitoring.agent
shfmt -w -l openwisp-monitoring/files/monitoring.init
shfmt -w -l openwisp-monitoring/files/openwisp-monitoring.hotplug

# format lua files
cd openwisp-monitoring/
lua-format -i --config=luaformat.config \
	files/sbin/*.lua \
	files/lib/openwisp-monitoring/*.lua \
	tests/*.lua \
	tests/test_files/*.lua
