#!/bin/bash
set -e

cd openwrt-openwisp-monitoring/tests/
lua test_dhcp.lua -v
lua test_interfaces.lua -v
lua test_utils.lua -v
lua test_neighbors.lua -v
lua test_resources.lua -v
lua test_wifi.lua -v
lua test_netjson_monitoring.lua -v
